### ISSUE TITLE
StreamIniDataParser does not respect AssignmentSpacer

### ISSUE THREAD

**Issue by glatzert** [rickyah/ini-parser#120]
Setting `Parser.Configuration.AssigmentSpacer` on a `StreamIniDataParser` instance to `""` or `null` won't have an effect on the output.

**Comment by caverna** [comment]
The fix done at https://github.com/rickyah/ini-parser/issues/32 should correct this behavior.
Please provide information (code perhaps?).

**Comment by rickyah** [comment]
The `StreamIniDataParser` is not supposed to output anything, it is used to parse an ini file from a stream, so we abstract the source of the ini file. What's  the exact problem you are having @glatzert ?

**Comment by glatzert** [comment]
Since StringDataParser was marked obsolete, I used StreamIniDataParser to write an IniFile.
And some of the settings just got ignored - this is my current code, so you get the Idea what I was doing.

public void Serialize(MyModel x, string targetFilePath)
        {
            var iniOutput = new IniData();

            iniOutput.Sections.AddSection(HeaderSectionName);
            // Add more sections and such

            string content;

            //Prepare content
            using (var ms = new MemoryStream())
            using (var sw = new StreamWriter(ms, _encoding))
            {
                var iniParser = new StreamIniDataParser();
                iniParser.Parser.Configuration.AssigmentSpacer = null;
                iniParser.WriteData(sw, iniOutput);
                sw.Flush();

                content = _encoding.GetString(ms.ToArray());
            }

            //Normalize Key=Value
            content = content.Replace(" = ", "=");

            //Remove empty lines before sections
            content = content.Replace("\r\n\r\n[", "\r\n[");
            File.WriteAllText(targetFilePath, content, _encoding);
        }

**Comment by rickyah** [comment]
Replace line
`iniParser.Parser.Configuration.AssigmentSpacer = null;`
with
 `iniOutput.Configuration.AssigmentSpacer = string.Empty;`

I probably should separate Formatting options from parsing options, they are together because in the first versions,  the different parsers were the responsible to write ini data to a string. Now the IniData structure is the one that writes a string representation of the IniData, that's why changing the Configuration for the data structure works, and changing the configuration for the parser doesn't.

**Comment by rboy1** [comment]
So I'm a little confused here, there are two configuration objects, one for Parser and for Config, which one are we supposed to use and when? Why not just one have one configuration object in the parser and use that for everything.

**Comment by rboy1** [comment]
I got it, looking at the code I see iniParser and iniOutput have their own Parsers unless the iniOutput was created by the iniParser. I think for clarity purposes there should be a constructor for IniData that should accept a IniDataParser as an input the same way FileIniDataParser accepts one otherwise without appropriate documentation this can get very confusing.

**Comment by rickyah** [comment]
IniParser has a configuration file used to know how he should parse files: the comment character to use, whether it is allowed to repeat sections, etc

That configuración file has to be used too to write the data contained on IniData to a string, and as the IniData has that responsibility, the configuration of the parser is copied to the IniData when you parse a file
 However you need to configure more settings when you write the ini file. The Assignment spacer for example. Those configurations only make sense to *write* the file that's why you have to set it on the IniData instance (iniOutput), not in the parser (iniParser)

**Comment by rickyah** [comment]
IniData accepting a parser as a parameter makes no sense to me: is the parser the one that creates the ini, not the ini creates itself using a dependency on a parser.

If you want to check the 3.0 branch, there are different configuration files that explain more semantically what each is used for

**Comment by rickyah** [comment]
I'm closing this because the original problem is fixed, but feel free to continue the conversation @rboy1

**Comment by rboy1** [comment]
I understand what you're saying but logically there is a problem here. There is a lack of documentation explicitly identifying that the configuration options need to set separately for reading and writing first.

A typical flow would look like:

                m_parser = new FileIniDataParser();
                m_parser.Parser.Configuration.CaseInsensitive = true; // We aren't case sensitive
                m_parser.Parser.Configuration.ThrowExceptionsOnError = true; // We want exceptions
                m_parser.Parser.Configuration.SectionRegex = new System.Text.RegularExpressions.Regex(@"^(\s*?)\[{1}\s*.+\s*\](\s*?)$"); // We'll take any character in the section name, by default it limits the characters to only certain characters

                if (File.Exists(file)) // If it exists then load it else create a new configuration and if we write something to it, it will be saved
                    Config = m_parser.ReadFile(file, Encoding.UTF8); // This config object will inherit the parser from the reader
                else
                {
                    Config = new IniData(); // Create a new object that we will write into a file later
                    Config.Configuration = m_parser.Parser.Configuration; // Lets use the same parser configuration for writing a new file as the one we use for reading the file
                }

This is the right way to do it. You see the issue here, apart from there being no documentation on this, it's not intuitive to new users that the Configuration object from the Parser needs to be assigned to a new object which will be used for writing.

When Reading a file it automatically inherits the object. That's why I'm suggesting that for IniData() there should be constructor with a Configuration object passed. That way the same object can be passed to the reader and writer keeping the configuration in sync.

**Comment by rickyah** [comment]
You are tottally right @rboy1, but I prefer to leave it as it is for 2.x and do a better job for the 3.x version
