### ISSUE TITLE
Escaping = in the ini file

### ISSUE THREAD

**Issue by Bluscream** [rickyah/ini-parser#179]
I have a ini like this

```ini
[templates]
newcomplaint = Neue Beschwerde über {target} von {source}: {message}

[servers]
iUnUtUG0lCiYpjkxeUy7Df4EmSY= = 2738828

[clients]
```

How can i escape the `=` in `iUnUtUG0lCiYpjkxeUy7Df4EmSY=`?

```
<07:26:41> "Boiiiing": !complaintreminder get
<07:26:41> "[ILoveRadio] ILoveRadio1": iUnUtUG0lCiYpjkxeUy7Df4EmSY=:
<07:26:48> "Boiiiing": !complaintreminder get iUnUtUG0lCiYpjkxeUy7Df4EmSY=
<07:26:48> "[ILoveRadio] ILoveRadio1": iUnUtUG0lCiYpjkxeUy7Df4EmSY=:
<07:26:53> "Boiiiing": !complaintreminder get iUnUtUG0lCiYpjkxeUy7Df4EmSY\=
<07:26:53> "[ILoveRadio] ILoveRadio1": iUnUtUG0lCiYpjkxeUy7Df4EmSY\=:
<07:27:00> "Boiiiing": !complaintreminder get iUnUtUG0lCiYpjkxeUy7Df4EmSY=
<07:27:00> "[ILoveRadio] ILoveRadio1": iUnUtUG0lCiYpjkxeUy7Df4EmSY=:
<07:27:08> "Boiiiing": !complaintreminder get iUnUtUG0lCiYpjkxeUy7Df4EmSY
<07:27:08> "[ILoveRadio] ILoveRadio1": iUnUtUG0lCiYpjkxeUy7Df4EmSY: = 2738828
```

**Comment by rickyah** [comment]
You can't escape the first value of =, at least w/out touching the source code. You can, however, use the string " =" (one white space at the beginning)  as the separator between properties to parse your ini file successfully. The bad news  you need to get the latest v3.0/develop version which is in development and thus unstable, because version2 does not support using strings as separator, only a char

I don't know about your needs, but if you are not confortable dropping non tested code into your codebase, I'll suggest to stick to version 2, and _preprocess your file_ before using the parser: substitute the string " = " (with spaces before and after the = sign)  with another character not used in your ini file that can be used as a separator, and assign that character to `IniParserConfiguration. KeyValueAssigmentChar` (https://github.com/rickyah/ini-parser/blob/development/src/IniFileParser/Model/Configuration/IniParserConfiguration.cs#L191)

**Comment by Bluscream** [comment]
Thanks :)
