### ISSUE TITLE
Invalid NuGet package

### ISSUE THREAD

**Issue by mikasoukhov** [rickyah/ini-parser#232]
A target framework is not specified in nuspec. VS does not understand it is compatible with non-FW projects (like core or standard).

**Comment by DevD4v3** [comment]
What is the problem itself? I do not understand.

**Comment by mikasoukhov** [comment]
See dependencies of your package https://www.nuget.org/packages/ini-parser-netstandard2.1 and the same tab of original. No dependencies mostly means wrong. Like in that case.

Anyway the project is dead, and I stopped using it at all.

**Comment by DevD4v3** [comment]
ini-parser has no dependencies, that's why it comes out "no dependencies". The original [ini-parser package](https://www.nuget.org/packages/ini-parser/2.5.2) is only compatible with **.NET Framework 2.0**.

Moreover, someone added only **.NET Standard 2.0** support and published it here: https://www.nuget.org/packages/ini-parser-netstandard/ but what I did is to create a new package with [.NET Standard 2.1]( https://www.nuget.org/packages/ini-parser-netstandard2.1 ) support. 

Try using my package and see if it solves your problem.

**Comment by mikasoukhov** [comment]
You did wrong. Standard 2.0 make's compatibility with Standard 2.1.

Problem in nuspec. This better contact guys with NuGet team then will explain it better.

**Comment by MrDave1999** [comment]
Standard 2.1 adds new functions to the API that are not in Standard 2.0... That is, Standard 2.0 is not compatible with Standard 2.1. For example, .NET Standard 2.0 is not compatible with .NET Core 3.x.

Here is a list of the platforms that support [Standard 2.0](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md#platform-support) and [Standard 2.1](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.1.md#platform-support).

A NuGet package can target multiple target platforms (.net standard, .net core, .net framework, etc.), in this case, the package I uploaded to NuGet, has support for both Standard 2.0 and Standard 2.1. 

Now that ini-parser has support for both standards (2.0/2.1), there will be more compatibility. For example, an application with .NET Core 2.x will be able to call the ini-parser library or if the application targets .NET Core 3.x it will also be able to call the ini-parser library.

**Comment by DevD4v3** [comment]
Yes, the original package: https://www.nuget.org/packages/ini-parser/2.5.2 does not include the target framework in the .nuspec file. Although the .nuspec only serves to provide information to consumers, so this should not cause problems when installing the package. Please note that this package is old and only has support for .NET Framework 2.0.

Please try using my package and let me know if your problem is resolved.
