### ISSUE TITLE
Distribution of my app

### ISSUE THREAD

**Issue by rfresh737** [rickyah/ini-parser#73]
Is there anything I have to do when I build my app to run outside of VS 2013?

When I run it as a stand alone windows app, at the part of the code where I'm using your module, I get a runtime error:
System.IO.FileNotFoundException: Could not load file or assembly 'INIFileParser, Version=2.0.4.0

This doesn't happen inside my VS 2013 IDE.

Thank you...

**Comment by Svetomech** [comment]
Find the assembly reference in your project explorer window, set its property "Copy Local" to true.

**Comment by rfresh737** [comment]
I don't have the iniparser.dll file !! I don't see it in your source files.

**Comment by rfresh737** [comment]
I added the INIFileParser.cs file to my project folder. Now I see the INIFileparser.dll file in my solution explorer but I still don't see the .cs file. I don't see anything about "Copy local".

I'm really confused as to how all of this works.

**Comment by rickyah** [comment]
The problem is that your app cannot find the IniFileParser.dll file. That's the file created when you compile this project. If you use the dll file you don't need to add any .cs file.

In your application you should have a reference to the IniFileParser.dll file, otherwise you wouldn't be able to use it even in visual studio. When you run the app in VS, it automatically copies that dll file to the same folder as your application .exe. You need to compile your solution, search in the folder where your application is generated and you should see both your .exe and IniFileParser.dll. You need BOTH to be in the same folder to execute the application.

Of course if you have more dependencies to other libraries (other dll files) this also applies to them, so you need to have all your dll files in the same folder as the executable file of your application

**Comment by rfresh737** [comment]
OK, got it...thanks...
