### ISSUE TITLE
Convenience methods for accessing keys

### ISSUE THREAD

**Issue by mbcrawfo** [rickyah/ini-parser#84]
Not really an issue, but seeing if you are interested in these features.  I'm planning to add some convenience methods so that you can get a key using a single string (eg "MySection:MyKey") and possibly also generic methods to automatically parse a key for types that have a static Parse method.

I can easily add these as extension methods for myself, but if you are interested in having them as part of the library I'll add them directly to IniData, set up some unit tests and do a pull request when finished.

**Comment by rickyah** [comment]
@mbcrawfo any addition and PRs are welcome.

However, regarding the extension methods you mentioned you want to add to IniData I would actually do prefer them to be extension methods. I didn't bother to create functions to converting string keys to values because there are many publicly available (e.g. http://extensionmethod.net/csharp/string/parse-t or http://stackoverflow.com/questions/1465855/how-to-dynamically-cast-an-object-of-type-string-to-an-object-of-type-t/1465930#1465930) and because parsing values is usually tricker that it seems.

For instance, this example:
```csharp
string floatValue = "42.5";
float number = Convert.ChangeType(floatValue, typeof(float));
```

You would expect `number` to contain the value 42.5, but on my system it contains the value 425. The reason is that I'm Spanish, and in Spain the decimal separator is actually not a point but a comma; points are used as thousand group separators (e.g 10.000,45) 
So the string needs to be "42,5" in order to be parsed correctly. This is something related to which 'System.Globalization.CultureInfo' are defined as default for your system. You can bypass this behavior using the overloaded method ChangeType that accepts an `IFormatProvider` object to parse an string containing a number with scientific notation (points for decimal, no group separators)

As you can see the rabbit hole is deeper that it seemed in first place :smile:

**Comment by mbcrawfo** [comment]
The method that I implemented takes optional params, and uses reflection to look for a static Parse method taking a string and the params you passed, so you can access all of the Parse overloads to handle cultural formatting and so on.  For example,

    var data = new IniDataParser().Parse("key = 42.5");
    int key = data.GetKeyAndParse<int>("key");  // calls Int32.Parse(string)
    key = data.GetKeyAndParse<int>("key", CultureInfo.CreateSpecificCulture("en-US"));  // calls Int32.Parse(string, IFormatProvider)

Now that I've written it and tested it, though, I'm not sure that I like it.  At most it saves maybe 1 or 2 LOC, and I'm not sure that it's actually clear what the method is doing unless you read its documentation.  So unless you really want the get and parse method, I think I will just submit the PR without them.  :wink:
